// +build !ignore_autogenerated_openshift

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package network

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetwork) DeepCopyInto(out *ClusterNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetwork.
func (x *ClusterNetwork) DeepCopy() *ClusterNetwork {
	if x == nil {
		return nil
	}
	out := new(ClusterNetwork)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkList) DeepCopyInto(out *ClusterNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkList.
func (x *ClusterNetworkList) DeepCopy() *ClusterNetworkList {
	if x == nil {
		return nil
	}
	out := new(ClusterNetworkList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressNetworkPolicy) DeepCopyInto(out *EgressNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new EgressNetworkPolicy.
func (x *EgressNetworkPolicy) DeepCopy() *EgressNetworkPolicy {
	if x == nil {
		return nil
	}
	out := new(EgressNetworkPolicy)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressNetworkPolicyList) DeepCopyInto(out *EgressNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EgressNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new EgressNetworkPolicyList.
func (x *EgressNetworkPolicyList) DeepCopy() *EgressNetworkPolicyList {
	if x == nil {
		return nil
	}
	out := new(EgressNetworkPolicyList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressNetworkPolicyPeer) DeepCopyInto(out *EgressNetworkPolicyPeer) {
	*out = *in
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new EgressNetworkPolicyPeer.
func (x *EgressNetworkPolicyPeer) DeepCopy() *EgressNetworkPolicyPeer {
	if x == nil {
		return nil
	}
	out := new(EgressNetworkPolicyPeer)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressNetworkPolicyRule) DeepCopyInto(out *EgressNetworkPolicyRule) {
	*out = *in
	out.To = in.To
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new EgressNetworkPolicyRule.
func (x *EgressNetworkPolicyRule) DeepCopy() *EgressNetworkPolicyRule {
	if x == nil {
		return nil
	}
	out := new(EgressNetworkPolicyRule)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressNetworkPolicySpec) DeepCopyInto(out *EgressNetworkPolicySpec) {
	*out = *in
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]EgressNetworkPolicyRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new EgressNetworkPolicySpec.
func (x *EgressNetworkPolicySpec) DeepCopy() *EgressNetworkPolicySpec {
	if x == nil {
		return nil
	}
	out := new(EgressNetworkPolicySpec)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSubnet) DeepCopyInto(out *HostSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new HostSubnet.
func (x *HostSubnet) DeepCopy() *HostSubnet {
	if x == nil {
		return nil
	}
	out := new(HostSubnet)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSubnetList) DeepCopyInto(out *HostSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new HostSubnetList.
func (x *HostSubnetList) DeepCopy() *HostSubnetList {
	if x == nil {
		return nil
	}
	out := new(HostSubnetList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetNamespace) DeepCopyInto(out *NetNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new NetNamespace.
func (x *NetNamespace) DeepCopy() *NetNamespace {
	if x == nil {
		return nil
	}
	out := new(NetNamespace)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetNamespaceList) DeepCopyInto(out *NetNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new NetNamespaceList.
func (x *NetNamespaceList) DeepCopy() *NetNamespaceList {
	if x == nil {
		return nil
	}
	out := new(NetNamespaceList)
	x.DeepCopyInto(out)
	return out
}
