// +build !ignore_autogenerated_openshift

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	api_v1 "k8s.io/kubernetes/pkg/api/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomDeploymentStrategyParams) DeepCopyInto(out *CustomDeploymentStrategyParams) {
	*out = *in
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]api_v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new CustomDeploymentStrategyParams.
func (x *CustomDeploymentStrategyParams) DeepCopy() *CustomDeploymentStrategyParams {
	if x == nil {
		return nil
	}
	out := new(CustomDeploymentStrategyParams)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentCause) DeepCopyInto(out *DeploymentCause) {
	*out = *in
	if in.ImageTrigger != nil {
		in, out := &in.ImageTrigger, &out.ImageTrigger
		if *in == nil {
			*out = nil
		} else {
			*out = new(DeploymentCauseImageTrigger)
			**out = **in
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentCause.
func (x *DeploymentCause) DeepCopy() *DeploymentCause {
	if x == nil {
		return nil
	}
	out := new(DeploymentCause)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentCauseImageTrigger) DeepCopyInto(out *DeploymentCauseImageTrigger) {
	*out = *in
	out.From = in.From
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentCauseImageTrigger.
func (x *DeploymentCauseImageTrigger) DeepCopy() *DeploymentCauseImageTrigger {
	if x == nil {
		return nil
	}
	out := new(DeploymentCauseImageTrigger)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentCondition) DeepCopyInto(out *DeploymentCondition) {
	*out = *in
	out.LastUpdateTime = in.LastUpdateTime.DeepCopy()
	out.LastTransitionTime = in.LastTransitionTime.DeepCopy()
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentCondition.
func (x *DeploymentCondition) DeepCopy() *DeploymentCondition {
	if x == nil {
		return nil
	}
	out := new(DeploymentCondition)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (x *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfig)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigList) DeepCopyInto(out *DeploymentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigList.
func (x *DeploymentConfigList) DeepCopy() *DeploymentConfigList {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfigList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigRollback) DeepCopyInto(out *DeploymentConfigRollback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.UpdatedAnnotations != nil {
		in, out := &in.UpdatedAnnotations, &out.UpdatedAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Spec = in.Spec
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigRollback.
func (x *DeploymentConfigRollback) DeepCopy() *DeploymentConfigRollback {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfigRollback)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigRollbackSpec) DeepCopyInto(out *DeploymentConfigRollbackSpec) {
	*out = *in
	out.From = in.From
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigRollbackSpec.
func (x *DeploymentConfigRollbackSpec) DeepCopy() *DeploymentConfigRollbackSpec {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfigRollbackSpec)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigSpec) DeepCopyInto(out *DeploymentConfigSpec) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make(DeploymentTriggerPolicies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		if *in == nil {
			*out = nil
		} else {
			*out = new(api_v1.PodTemplateSpec)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigSpec.
func (x *DeploymentConfigSpec) DeepCopy() *DeploymentConfigSpec {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfigSpec)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigStatus) DeepCopyInto(out *DeploymentConfigStatus) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		if *in == nil {
			*out = nil
		} else {
			*out = new(DeploymentDetails)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DeploymentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigStatus.
func (x *DeploymentConfigStatus) DeepCopy() *DeploymentConfigStatus {
	if x == nil {
		return nil
	}
	out := new(DeploymentConfigStatus)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDetails) DeepCopyInto(out *DeploymentDetails) {
	*out = *in
	if in.Causes != nil {
		in, out := &in.Causes, &out.Causes
		*out = make([]DeploymentCause, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDetails.
func (x *DeploymentDetails) DeepCopy() *DeploymentDetails {
	if x == nil {
		return nil
	}
	out := new(DeploymentDetails)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentLog) DeepCopyInto(out *DeploymentLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentLog.
func (x *DeploymentLog) DeepCopy() *DeploymentLog {
	if x == nil {
		return nil
	}
	out := new(DeploymentLog)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentLogOptions) DeepCopyInto(out *DeploymentLogOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.SinceSeconds != nil {
		in, out := &in.SinceSeconds, &out.SinceSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.SinceTime != nil {
		in, out := &in.SinceTime, &out.SinceTime
		if *in == nil {
			*out = nil
		} else {
			*out = new(meta_v1.Time)
			**out = (*in).DeepCopy()
		}
	}
	if in.TailLines != nil {
		in, out := &in.TailLines, &out.TailLines
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.LimitBytes != nil {
		in, out := &in.LimitBytes, &out.LimitBytes
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentLogOptions.
func (x *DeploymentLogOptions) DeepCopy() *DeploymentLogOptions {
	if x == nil {
		return nil
	}
	out := new(DeploymentLogOptions)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentRequest) DeepCopyInto(out *DeploymentRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ExcludeTriggers != nil {
		in, out := &in.ExcludeTriggers, &out.ExcludeTriggers
		*out = make([]DeploymentTriggerType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentRequest.
func (x *DeploymentRequest) DeepCopy() *DeploymentRequest {
	if x == nil {
		return nil
	}
	out := new(DeploymentRequest)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStrategy) DeepCopyInto(out *DeploymentStrategy) {
	*out = *in
	if in.CustomParams != nil {
		in, out := &in.CustomParams, &out.CustomParams
		if *in == nil {
			*out = nil
		} else {
			*out = new(CustomDeploymentStrategyParams)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.RecreateParams != nil {
		in, out := &in.RecreateParams, &out.RecreateParams
		if *in == nil {
			*out = nil
		} else {
			*out = new(RecreateDeploymentStrategyParams)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.RollingParams != nil {
		in, out := &in.RollingParams, &out.RollingParams
		if *in == nil {
			*out = nil
		} else {
			*out = new(RollingDeploymentStrategyParams)
			(*in).DeepCopyInto(*out)
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStrategy.
func (x *DeploymentStrategy) DeepCopy() *DeploymentStrategy {
	if x == nil {
		return nil
	}
	out := new(DeploymentStrategy)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentTriggerImageChangeParams) DeepCopyInto(out *DeploymentTriggerImageChangeParams) {
	*out = *in
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.From = in.From
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentTriggerImageChangeParams.
func (x *DeploymentTriggerImageChangeParams) DeepCopy() *DeploymentTriggerImageChangeParams {
	if x == nil {
		return nil
	}
	out := new(DeploymentTriggerImageChangeParams)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentTriggerPolicy) DeepCopyInto(out *DeploymentTriggerPolicy) {
	*out = *in
	if in.ImageChangeParams != nil {
		in, out := &in.ImageChangeParams, &out.ImageChangeParams
		if *in == nil {
			*out = nil
		} else {
			*out = new(DeploymentTriggerImageChangeParams)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentTriggerPolicy.
func (x *DeploymentTriggerPolicy) DeepCopy() *DeploymentTriggerPolicy {
	if x == nil {
		return nil
	}
	out := new(DeploymentTriggerPolicy)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecNewPodHook) DeepCopyInto(out *ExecNewPodHook) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]api_v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new ExecNewPodHook.
func (x *ExecNewPodHook) DeepCopy() *ExecNewPodHook {
	if x == nil {
		return nil
	}
	out := new(ExecNewPodHook)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleHook) DeepCopyInto(out *LifecycleHook) {
	*out = *in
	if in.ExecNewPod != nil {
		in, out := &in.ExecNewPod, &out.ExecNewPod
		if *in == nil {
			*out = nil
		} else {
			*out = new(ExecNewPodHook)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.TagImages != nil {
		in, out := &in.TagImages, &out.TagImages
		*out = make([]TagImageHook, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleHook.
func (x *LifecycleHook) DeepCopy() *LifecycleHook {
	if x == nil {
		return nil
	}
	out := new(LifecycleHook)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecreateDeploymentStrategyParams) DeepCopyInto(out *RecreateDeploymentStrategyParams) {
	*out = *in
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		if *in == nil {
			*out = nil
		} else {
			*out = new(LifecycleHook)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Mid != nil {
		in, out := &in.Mid, &out.Mid
		if *in == nil {
			*out = nil
		} else {
			*out = new(LifecycleHook)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		if *in == nil {
			*out = nil
		} else {
			*out = new(LifecycleHook)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new RecreateDeploymentStrategyParams.
func (x *RecreateDeploymentStrategyParams) DeepCopy() *RecreateDeploymentStrategyParams {
	if x == nil {
		return nil
	}
	out := new(RecreateDeploymentStrategyParams)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingDeploymentStrategyParams) DeepCopyInto(out *RollingDeploymentStrategyParams) {
	*out = *in
	if in.UpdatePeriodSeconds != nil {
		in, out := &in.UpdatePeriodSeconds, &out.UpdatePeriodSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.IntervalSeconds != nil {
		in, out := &in.IntervalSeconds, &out.IntervalSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int64)
			**out = **in
		}
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		if *in == nil {
			*out = nil
		} else {
			*out = new(intstr.IntOrString)
			**out = **in
		}
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		if *in == nil {
			*out = nil
		} else {
			*out = new(intstr.IntOrString)
			**out = **in
		}
	}
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		if *in == nil {
			*out = nil
		} else {
			*out = new(LifecycleHook)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		if *in == nil {
			*out = nil
		} else {
			*out = new(LifecycleHook)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new RollingDeploymentStrategyParams.
func (x *RollingDeploymentStrategyParams) DeepCopy() *RollingDeploymentStrategyParams {
	if x == nil {
		return nil
	}
	out := new(RollingDeploymentStrategyParams)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagImageHook) DeepCopyInto(out *TagImageHook) {
	*out = *in
	out.To = in.To
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new TagImageHook.
func (x *TagImageHook) DeepCopy() *TagImageHook {
	if x == nil {
		return nil
	}
	out := new(TagImageHook)
	x.DeepCopyInto(out)
	return out
}
